#!/usr/bin/bash

#lua main.lua main
if [ -z $1 ]; then
    echo "Orb Interactive Interpreter (OII: use '--help' for help):"
    lua -e "
    local function endings(str)
        local out = {}
        for s = 1, #str do
            out[#out+1] = str:sub(s,s)
        end
        return out[#out-1]..out[#out]
    end
    Variables = {Global = {}, Static = {},Temporary = {}};
    while true do
        local writevar = '>'
        local exe = ''
        Blocks = require('src/Blocks');
        Transpiler = require('src/transpiler');
        Runtime = require('src/runtime');
        syntax = {};
        io.write(writevar..' '); 
        syntax[#syntax+1] = io.read();
        if endings(syntax[#syntax]) == ':{' then
            repeat
                io.write(writevar..writevar..' ')
                local s = io.read()
                syntax[#syntax+1] = s
            until s == '}'
        end
        Runtime.run();
        translated = Transpiler.translate();
        for _,i in pairs(translated) do
            for s,t in pairs(i) do
                exe = exe..t
            end
            exe = exe..'\n'
        end
        load(exe)()
    end
    "
else
    lua src/main.lua $1
fi
