#!/usr/bin/bash

RED='\033[0;31m'
RESET='\033[0m'

if [ -z $1 ]; then
    echo -e "Orb: ${RED}<compiler>${RESET} error:\ntraceback:\n\t[orb]: no input file specified"
else
    lua src/main.lua "-c" $1 $2 $3 $4 $5 $6 $7 $8 $9 "orbc"
fi
