local Tokens = {}

Tokens = {
--------------------[Keys]-----------------------
    OTOKEN_KEY_EOF = function() return "<EOF>" end,
    OTOKEN_KEY_STATMENT = function() return "<STATMENT>" end,
    OTOKEN_KEY_COMMENT = function() return "<COMMENT>" end,
    OTOKEN_KEY_METHOD = function() return "<METHOD>" end,
    OTOKEN_KEY_ASSIGN = function() return "->" end,
    OTOKEN_KEY_EOL = function() return "<EOL>" end,
    OTOKEN_KEY_DEFCALL = function() return "@" end,
    OTOKEN_KEY_DEF_VARCALL = function() return "$" end,
    OTOKEN_KEY_LENGTH = function() return "#" end,
    OTOKEN_KEY_ESCAPE = function() return "\\" end,
    OTOKEN_KEY_OR = function() return "||" end,
    OTOKEN_KEY_AND = function() return "&&" end,
    --OTOKEN_KEY_IDENTIFIER = function() return ":%w+" end,
--------------[Keywords (17 for now)]---------------
    OTOKEN_KEYWORD_FUNCTION = function() return "FUNC" end,
    OTOKEN_KEYWORD_IF = function() return "IF" end,
    OTOKEN_KEYWORD_ELIF = function() return "ELIF" end,
    OTOKEN_KEYWORD_WHILE = function() return "WHILE" end,
    OTOKEN_KEYWORD_FOR = function() return "FOR" end,
    OTOKEN_KEYWORD_SET = function() return "SET" end,
    OTOKEN_KEYWORD_NIL = function() return "NIL" end,
    OTOKEN_KEYWORD_ELSE = function() return "ELSE" end,
    OTOKEN_KEYWORD_TRUE = function() return "TRUE"end,
    OTOKEN_KEYWORD_FALSE = function() return "FALSE" end,
    OTOKEN_KEYWORD_RETURN = function() return "RETURN" end,
    OTOKEN_KEYWORD_DEF = function() return "DEF" end,
    OTOKEN_KEYWORD_FORMAT = function() return "FORMAT" end,
    OTOKEN_KEYWORD_PUTLN = function() return "PUTLN" end,
    OTOKEN_KEYWORD_STATIC = function() return "STATIC" end,
    OTOKEN_KEYWORD_INCLUDING = function() return "INCLUDING" end,
------------------------[Others]-------------------------
    OTOKEN_TYPE_STRING = function() return "STRING" end,
    OTOKEN_TYPE_NUMBER = function() return "NUMBER" end,
    OTOKEN_TYPE_OPAREN = function() return "(" end,
    OTOKEN_TYPE_CPAREN = function() return ")" end,
    OTOKEN_TYPE_OBRACE = function () return "{" end,
    OTOKEN_TYPE_CBRACE = function () return "}" end,
    OTOKEN_TYPE_OBRACKET = function() return "[" end,
    OTOKEN_TYPE_CBRACKET = function() return "]" end,
    OTOKEN_TYPE_PLUS = function() return "+" end,
    OTOKEN_TYPE_MINUS = function() return "-" end,
    OTOKEN_TYPE_DIVIDE = function() return "/" end,
    OTOKEN_TYPE_MULTIPLY = function() return "*" end,
    OTOKEN_TYPE_MODULO = function() return "%" end,
    OTOKEN_TYPE_SQUOTE = function() return "'" end,
    OTOKEN_TYPE_DQUOTE = function() return '"' end,
    OTOKEN_TYPE_EXPONENT = function() return "^" end,
    OTOKEN_TYPE_EQUAL = function() return "=" end,
    OTOKEN_TYPE_PERIOD = function() return "." end,
    OTOKEN_TYPE_COLON = function() return ":" end,
    OTOKEN_TYPE_COMMA = function() return "," end,
    OTOKEN_TYPE_GTHAN = function() return ">" end,
    OTOKEN_TYPE_LTHAN = function() return "<" end,
    OTOKEN_TYPE_EPOINT = function() return "!" end,
    OTOKEN_TYPE_EOL = function() return ";" end,
    OTOKEN_TYPE_SPACE = function() return " " end,
--ANYTHING AFTER THIS POINT IS JUST TO INCLUDING EVERY CHARACTER ON A STANDARD KEYBOARD
    OTOKEN_FILL_QMARK = function() return "?" end,
    OTOKEN_FILL_SQUIGGLE = function() return "~" end,
    OTOEKN_FILL_APOSTROPHE = function() return "`" end,
    OTOKEN_FILL_UNDERSCORE = function() return "_" end,
    OTOKEN_FILL_HALFOR = function() return "|" end,
    OTOKEN_FILL_HALFAND = function() return "&" end,
}

return Tokens
